# Project specific config

# Installed for linting the project
language: node_js

matrix:
  include:
    - os: linux
      env: ATOM_CHANNEL=stable
      node_js: "6"

    - os: linux
      env: ATOM_CHANNEL=beta
      node_js: "6"

    - os: osx
      env: ATOM_CHANNEL=stable
      node_js: "6"

# Generic setup follows
script: 'curl -Ls https://github.com/Arcanemagus/ci/raw/atomlinter/build-package.sh | sh'

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
